### ISSUE TITLE
Ошибка инициализации firebase при подключении 2гис

### ISSUE THREAD

**Issue by AntonMenshickov** [2gis/dgis_mobile_sdk_full#1]
При подключении в проект с установленным firebase плагином происходит ошибка "PlatformException(channel-error, Unable to establish connection on channel., null, null)"

`Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter ( 5510): #0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:210:7)
E/flutter ( 5510): <asynchronous suspension>
E/flutter ( 5510): #1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
E/flutter ( 5510): <asynchronous suspension>
E/flutter ( 5510): #2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter ( 5510): <asynchronous suspension>
E/flutter ( 5510): #3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:66:31)
E/flutter ( 5510): <asynchronous suspension>
E/flutter ( 5510): `

`Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4169], locale ru-RU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2022.3)
[√] IntelliJ IDEA Community Edition (version 2024.2)
[√] VS Code (version 1.93.1)
[√] Connected device (4 available)
[√] Network resources`

репозиторий для воспроизведения https://github.com/AntonMenshickov/2gis_firebase_error_reproduce

**Comment by Sameri11** [comment]
Привет!

На приложенном примере не воспроизводится. Мы поменяли конфигурацию Firebase под наше приложение, но это по идее не должно влиять на такую ошибку. 

Может быть, в логах есть еще что-то кроме указанной ошибки? В идеале, хотелось бы получить полный лог запуска.

**Comment by Sameri11** [comment]
Все же, можете предоставить полные логи с запуска? Пока неочевидно, что проблема с нашим SDK, потому что 1) не воспроизводится в нашей среде, 2) стектрейс ошибки все же уходит в Firebase.

Возможно, в полном логе будет что-то, что укажет на проблему в нашем SDK.

**Comment by AntonMenshickov** [comment]
@Sameri11 да, прикрепляю полный лог запуска
[run.txt](https://github.com/user-attachments/files/17109053/run.txt)

**Comment by AntonMenshickov** [comment]
ошибка появляется при инициализации firebase после добавления 2гис SDK

**Comment by Sameri11** [comment]
Есть ли возможность у вас проверить работоспособность на эмуляторе `x86_64` ?

**Comment by AntonMenshickov** [comment]
@Sameri11 проверил, на x86_64 не воспроизводится

**Comment by Sameri11** [comment]
Спасибо! У пакета в этой альфа версии обнаружились определенные проблемы именно с x86 архитектурой (с которой флаттер в целом так себе работает). Должны будут пофикситься с релизом стабильной версии. Пока рекомендуем пользоваться эмулятором на `x86_64`.
